<a href="https://colab.research.google.com/github/WillianVMR/PythonParaDataScienceAlura/blob/main/Python_Data_Science_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [ ]:
!python -V

Python 3.9.16


# 1.3 Trabalhando com arrays Numpy

In [ ]:
import numpy as np

In [ ]:
km = np.loadtxt('carros-km.txt')

In [ ]:
km

In [ ]:
anos = np.loadtxt('carros-anos.txt', dtype=int)

In [ ]:
anos

### Obtendo a quilometragem média por ano

In [ ]:
km_media = km / (2023 - anos)

In [ ]:
km_media

In [ ]:
type(km_media)

numpy.ndarray

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [ ]:
2 + 2

4

### Subtração ($-$)

In [ ]:
2-2

### Multiplicação ($*$)

In [ ]:
2 * 2

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [ ]:
2 / 2

In [ ]:
2 // 2

### Exponenciação ($**$)

In [ ]:
2 ** 3

### Resto da divisão ($\%$)

In [ ]:
10 % 3

In [ ]:
9 % 3

### Expressões matemáticas

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [ ]:
5 * 2

10

In [ ]:
_ + 3 * 2

16

In [ ]:
_ / 2

8.0

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [ ]:
ano_atual = 2019
ano_frabricacao = 1999
km_total = 44410.0

In [ ]:
ano_atual

2019

In [ ]:
ano_frabricacao

1999

In [ ]:
km_total

44410.0

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [ ]:
ano_atual = 2019
ano_frabricacao = 1999
km_total = 44410.0
km_media = km_total / (ano_atual - ano_frabricacao)

In [ ]:
km_media

2220.5

In [ ]:
km_total += km_media

In [ ]:
km_total

46630.5

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [ ]:
ano_atual, ano_frabricacao, km_total = 2019, 1999, 44410.0

In [ ]:
ano_atual

2019

In [ ]:
ano_frabricacao

1999

In [ ]:
km_total

44410.0

In [ ]:
ano_atual, ano_frabricacao, km_total = 2019, 1999, 44410.0
km_media = km_total / (ano_atual - ano_frabricacao)

# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [1]:
number_integer = 1

In [2]:
type(number_integer)

int

In [3]:
number_float = 1254.12

In [4]:
type(number_float)

float

### Booleanos

In [5]:
verdadeiro = True

In [6]:
type(verdadeiro)

bool

### Strings

In [7]:
texto = "Texto de exemplo"

In [8]:
texto_entre_aspas = 'Texto com texto entre "aspas"'

In [ ]:
texto_com_quebra_linha = '''
  Texto com quebra de linha
  Aqui fica texto com quebra de linha
'''

### None

In [9]:
nao_sei = None 

In [10]:
type(nao_sei)

NoneType

# 2.4 Conversão de tipos

In [18]:
a = 10
b = 20
c = 'Python é '
d = 'legal'

In [12]:
type(a)

int

In [13]:
type(b)

int

In [14]:
type(c)

str

In [15]:
type(d)

str

In [16]:
a + b

30

In [19]:
c + d 

'Python é legal'

In [20]:
# c + a 

TypeError: ignored

### Conversões de tipo

Funções int(), float(), str()

In [22]:
str(a)

'10'

In [23]:
c + str(a)

'Python é 10'

In [24]:
float(a)

10.0

In [25]:
pi = 3.141592

In [26]:
int(pi)

#pega somente o valor inteiro da int

3

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [ ]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [ ]:
# Isto é um comentário
ano_atual = 2019
ano_atual

In [ ]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

In [ ]:
'''Isto é um
comentário'''
ano_atual = 2019
ano_atual

In [ ]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

### Formatação de *strings*

## *str % valor*
https://docs.python.org/3.6/library/stdtypes.html#old-string-formatting

## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [27]:
print('Ola, {}!'.format('Rodrigo'))

Ola, Rodrigo!


In [28]:
print('Ola, {} login realizado {}!'.format('Rodrigo', 'Nickname Rod'))

Ola, Rodrigo login realizado Nickname Rod!


In [29]:
print('Ola, {nome} login realizado {nickname}!'.format(nome = 'Rodrigo', nickname = 'Nickname Rod'))

Ola, Rodrigo login realizado Nickname Rod!


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [30]:
nome = 'Rodrigo'
nickname = 'Nickname Rod'
print(f'Olá {nome} login realizado {nickname}')

Olá Rodrigo login realizado Nickname Rod


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [31]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

### Lista com tipos de dados variados

In [ ]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [32]:
'Rodas de liga' in Acessorios

True

In [33]:
'Rodas de liga' not in Acessorios

False

## *A + B*

Concatena as listas *A* e *B*.

In [35]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [36]:
A + B 

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

Tamanho da lista A.

In [37]:
len(A)

4

# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [38]:
A[0]

'Rodas de liga'

In [39]:
A[1]

'Travas elétricas'

In [40]:
A[2]

'Piloto automático'

In [41]:
A[-1]

'Bancos de couro'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [42]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [44]:
Acessorios[0:2]

['Rodas de liga', 'Travas elétricas']

In [45]:
Acessorios[:2]

['Rodas de liga', 'Travas elétricas']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena a lista *A*.

In [46]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [48]:
Acessorios.sort()
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

## *A.append(x)*

Adiciona o elemnto *x* no final da lista *A*.

In [50]:
Acessorios.append('Pneu')
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Pneu',
 'Pneu']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [52]:
Acessorios.pop(-1)
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Pneu']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [53]:
Acessorios_2 = Acessorios

In [54]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Pneu']

In [55]:
Acessorios_2.append('4 X 4')

In [56]:
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Pneu',
 '4 X 4']

In [57]:
Acesssorios_3 = Acessorios_2.copy()

In [58]:
Acesssorios_3.pop()


'4 X 4'

In [59]:
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Pneu',
 '4 X 4']

In [60]:
Acesssorios_3

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'Pneu']

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [61]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [63]:
for peca in Acessorios:
  print(peca)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [64]:
range(0, 10)

range(0, 10)

In [65]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [66]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [67]:
quadrado = []
for i in range(10):
  quadrado.append(i)
quadrado

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# 4.2 Loops aninhados

In [69]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [70]:
for lista in dados:
  for item in lista:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [72]:
Acessorios = []
for lista in dados:
  for item in lista:
    Acessorios.append(item)

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [73]:
# remoção de duplicatas de uma sequência

list(set(Acessorios))

['Travas elétricas',
 'Painel digital',
 'Vidros elétricos',
 'Freios ABS',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Central multimídia',
 'Teto panorâmico',
 'Câmera de estacionamento',
 'Piloto automático',
 'Câmbio automático',
 'Ar condicionado',
 'Rodas de liga',
 'Bancos de couro',
 'Controle de estabilidade',
 '4 X 4']

### List comprehensions

In [74]:
list(set([item for lista in dados for item in lista]))

['Travas elétricas',
 'Painel digital',
 'Vidros elétricos',
 'Freios ABS',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Central multimídia',
 'Teto panorâmico',
 'Câmera de estacionamento',
 'Piloto automático',
 'Câmbio automático',
 'Ar condicionado',
 'Rodas de liga',
 'Bancos de couro',
 'Controle de estabilidade',
 '4 X 4']

# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [76]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
for lista in dados:
  if (lista[2] == True):
    

### List comprehensions

In [77]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [ ]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

In [ ]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [79]:
import numpy as np

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [ ]:
np

### Importando todo o pacote e atribuindo um novo nome 

In [80]:
import numpy as np

In [82]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [83]:
from numpy import arange

In [84]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

In [3]:
import numpy as np


### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [86]:
km = np.array([1000, 2300, 4987, 1500])

In [87]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [89]:
km.dtype

dtype('int64')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [93]:
km = np.loadtxt(fname = 'carros-km.txt', dtype = int)

### Arrays com duas dimensões

In [94]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [95]:
Acessorios = np.array(dados)

In [96]:
km.shape

(258,)

In [97]:
Acessorios.shape

(3, 8)

### Comparando desempenho com listas

In [4]:
np_array = np.arange(1000000)

In [5]:
py_list = list(range(1000000))

In [6]:
%time for _ in range(100): np_array *= 2

CPU times: user 62.4 ms, sys: 838 µs, total: 63.3 ms
Wall time: 65 ms


In [7]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 9.29 s, sys: 2.52 s, total: 11.8 s
Wall time: 11.9 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [8]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [13]:
# idade = 2019 - anos

In [10]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [11]:
idade = 2019 - anos

In [12]:
idade

array([16, 28, 29,  0, 13])

### Operações entre arrays

In [14]:
km_media = km / idade

<ipython-input-14-502b13b90eb3>:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = km / idade


In [15]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

### Operações com arrays de duas dimensões

In [16]:
dados = np.array([km, anos])

In [17]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [18]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [20]:
dados[0] / (2019 - dados[1])

<ipython-input-20-fb26cb8e809a>:1: RuntimeWarning: invalid value encountered in true_divide
  dados[0] / (2019 - dados[1])


array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [21]:
dados


array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [23]:
contador = np.arange(10)

In [25]:
contador[0]

0

In [26]:
dados[1][2]

1990.0

In [27]:
dados[1, 2]

1990.0

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [28]:
contador = np.arange(10)

In [29]:
contador[1:4]

array([1, 2, 3])

In [30]:
contador[1:8:2]

array([1, 3, 5, 7])

In [31]:
contador[::2]

array([0, 2, 4, 6, 8])

In [32]:
dados


array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [33]:
dados[:, 1:4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [34]:
contador = np.arange(10)

In [35]:
contador


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
contador[contador > 5]

array([6, 7, 8, 9])

In [37]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [38]:
dados[1] > 2000

array([ True, False, False,  True,  True])

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [39]:
dados


array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [40]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [41]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [42]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [43]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [44]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [46]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [47]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [48]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
contador.reshape((5, 2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [51]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [54]:
info_carros = km + anos

In [55]:
np.array(info_carros).reshape((5,2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [56]:
dados_new = dados.copy()

In [57]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [58]:
dados_new.resize((3, 5), refcheck=False)

In [59]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [60]:
dados_new[2] = dados_new[0] / (2019 - dados[1])

<ipython-input-60-ad686ed0746b>:1: RuntimeWarning: invalid value encountered in true_divide
  dados_new[2] = dados_new[0] / (2019 - dados[1])


# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [61]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [62]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [65]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [66]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [68]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis = 1)

In [70]:
np.mean(dataset[:, 1])

44499.41472868217

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [71]:
np.std(dataset[:, 1])

39859.82699005149

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [72]:
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [73]:
np.sum(dataset, axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])